version: '3'

services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:7.0.15-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  worker:
    build: .
    command: bundle exec sidekiq
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - redis
  web:
    build: .
    entrypoint: ["bash", "./setup_app.sh"]
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    environment:
      RAILS_ENV: development
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    profiles:
      - development
  test:
    build: .
    entrypoint: ["bash", "./setup_app.sh"]
    command: bundle exec rspec
    volumes:
      - .:/app
    depends_on:
      - db
      - redis 
    environment:
      RAILS_ENV: test
    env_file:
      - ./.env
    profiles:
      - test

volumes:
  postgres:
  redis_data:
